const GeoLayout gammaheadwing_Wing_Cap_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gammaheadwing_Wing_Cap_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gammaheadwing_Wing_Cap_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gammaheadwing_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gammaheadwing_Wing_Cap_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, gammaheadwing_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_ALPHA, gammaheadwing_Wing_Cap_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_ALPHA, gammaheadwing_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gammaheadwing_Wing_Cap_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gammaheadwing_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gammaheadwing_Wing_Cap_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gammaheadwing_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout gammaheadwing_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 75),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, gammaheadwing_Wing_Cap_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_ALPHA, gammaheadwing_Wing_Cap_mesh_layer_4),
							GEO_DISPLAY_LIST(LAYER_ALPHA, gammaheadwing_Wings_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, gammaheadwing_Wing_Cap_Switch_opt1),
					GEO_BRANCH(1, gammaheadwing_Wing_Cap_Switch_opt2),
					GEO_BRANCH(1, gammaheadwing_Wing_Cap_Switch_opt3),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, gammaheadwing_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, gammaheadwing_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, gammaheadwing_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
