extern const GeoLayout gammaheadmetal_Metal_Cap_State_Switch_opt1[];
extern const GeoLayout gammaheadmetal_Metal_Cap_State_Switch_opt2[];
extern const GeoLayout gammaheadmetal_Metal_Cap_State_Switch_opt3[];
extern const GeoLayout gammaheadmetal_geo[];
extern Lights1 gammaheadmetal_Metal__CAP__lights;
extern Lights1 gammaheadmetal_Metal__METAL__lights;
extern u8 gammaheadmetal_Metal_Shade_rgba16_rgba16[];
extern u8 gammaheadmetal_Metal_Light_rgba16_rgba16[];
extern u8 gammaheadmetal_Metal_Shade_rgba16_rgba16_copy[];
extern u8 gammaheadmetal_Metal_Light_rgba16_rgba16_copy[];
extern Vtx gammaheadmetal_Metal_Cap_DL_mesh_layer_1_vtx_0[370];
extern Gfx gammaheadmetal_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Gfx mat_gammaheadmetal_Metal__CAP_[];
extern Gfx mat_revert_gammaheadmetal_Metal__CAP_[];
extern Gfx mat_gammaheadmetal_Metal__METAL_[];
extern Gfx mat_revert_gammaheadmetal_Metal__METAL_[];
extern Gfx gammaheadmetal_Metal_Cap_DL_mesh_layer_1[];
extern Gfx gammaheadmetal_Metal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx gammaheadmetal_material_revert_render_settings[];
